### ISSUE TITLE
For/Having/With redundancy

### ISSUE THREAD

**Issue by cherrydev** [ChrisEdwards/Fluency#10]
Unless I'm really mis-reading the API docs and source code for DynamicFluentBuilder, For(), Having() and With() all do exactly the same things.  What is the purpose of this?

**Comment by ChrisEdwards** [comment]
It's simply to make it more readable.  You can use any of those words as the context dictates.

**Comment by cherrydev** [comment]
Well, DRY (Don't Repeat Yourself) is part of my software development philosophy and repeating yourself in an API seems to make it more complicated rather than less. This is your software and your decision, of course, but I suggest that if you investigate other well-adopted APIs (especially other fluent APIs) you probably won't see any examples of duplicate methods that do exactly the same thing.

Personally, when I saw the example that had For, Having and With in it, my response was "wait, what's the difference between these?  They must do different things."  When I read the API docs and saw they were all exactly the same, my next response was, "this must have been copy and pasted and then never updated to match the real methods."  It wasn't until I read the source code that I understood that they did, indeed, all do the same thing.

**Comment by nrjohnstone** [comment]
Unless I misunderstand Chris, Fluency's main use case is testing. If you are applying DRY in testing then you are missing the point of DRY, since it's not purely about making sure you have no copy-paste code.
Unit Tests should be intent revealing and read like prose, and having fluent methods such as For() Having() and With() are key to helping write DAMP tests.

This should be closed in my opinion, as the methods are perfectly valid.

**Comment by ChrisEdwards** [comment]
Well stated. You are correct Nathan. Its all about making the code read well. The principle is to favor readability of tests over duplication in the Fluency framework.
